name: Docker
on: [workflow_dispatch]

jobs:
    docker-job:
        runs-on: ubuntu-latest
        container:
            image: node:20.3-alpine3.17
            env:
              API_URL: url.com
            ports:
              - 80
            options: --cpus 1
        steps:
          - name: Log Node and OS Versions
            run: |
              node -v
              cat /etc/os-release
          - name: Log Env
            run: echo $API_URL
          - name: Container in a Step
            uses: docker://node:18.16-alpine3.17
            with:
                entrypoint: /usr/local/bin/node
                args: -p 2+3
          - name: Lognode version
            uses: docker://node:18.16-alpine3.17
            with:
                args: -v